### ISSUE TITLE
High GPU usage

### ISSUE THREAD

**Issue by mirh** [KarlitosVII/trilogy-save-editor#5]
I get 30% usage on a RTX 3060, as long as the editor is not minimized. 
It's not critical, but it seems very very strange.

**Comment by KarlitosVII** [comment]
It is a bug in my Opengl backend.
I found a workaround, the new version should works.

**Comment by mirh** [comment]
Mhh nope. 
CPU is more or less fine (even though I'm not sure such a simple application is really supposed to use ~2% of cpu sitting there doing nothing), GPU is still super used.

**Comment by KarlitosVII** [comment]
CPU usage is working as intended because it is immediate GUI instead of more traditional retained mode. And it use less than 1% GPU for me so...

**Comment by mirh** [comment]
I don't really know what to say. 
It happens with both the intel igp, and the nvidia gpu. 
And I couldn't check in safe mode because it immediately crashes (I guess it's the graphics api or something missing there)

**Comment by Mashrien** [comment]
![TSE high gpu](https://user-images.githubusercontent.com/29497715/119093097-e0c2cc00-b9d4-11eb-94bd-5d71a3fd4022.png)
It's still an issue as of 1.5.0 with a 2080super, holds ~30% gpu usage. 4k/60 video playback only uses ~35%

**Comment by KarlitosVII** [comment]
Can you tell me if this is fixed in 1.6.1 ?

**Comment by mirh** [comment]
GPU usage is now in the neighbourhood of 10% (rather than 30%), but still it's crazy that there is usage like at all. 
Also.... it seems kind of lame to require \*vulkan\* from such a simple UI, for games themselves that could technically even work with older hardware.

**Comment by Mashrien** [comment]
It's not fixed completely. It's down to ~18% on a 2080super..
However, it IS "fixed enough"- It's 18% on the lowest P-state of the gpu, meaning it's no longer causing the GPU to clock-up.
Meaning no power increased power draw, no increased heat causing the fans to ramp up.

This is very much a satisfactory resolution considering the language and drawing backend/api chosen for the UI.

Thanks for this Karlitos :)

**Comment by KarlitosVII** [comment]
Thank you. :)

Indeed, Rust doesn't have a lot of GUI libraries but I could use GTK or a web-view based interface. But, I choose to use Imgui because it is well suited for directly edit big chunk of data like save game are. This is why other save editors use Imgui too (CPSE for Cyberpunk 2077). It's quite customizable and more importantly it's really enjoyable to code with. You can make a complex UI in a few lines of code. Furthermore, it is very reactive. For example, Gibbed's editor can take few second to open a save or to show a collection of hundred entries because in retained GUI you have to refresh the view each time data changed or use proxy view or whatever that can slow down the UI.

> The GUI is anything but simple, far as I can tell he's actually rendering the UI on the GPU itself using opengl/vulkan, a proper in-game HUD being used to create a GUI for the app. The fact he got it down to <20% on a 300mhz clocked gpu is impressive, imo.

It's not that complicated, I just use `Dear Imgui` on a graphical back-end. It's very lightweight and >10% GPU usage is really a bug.
For comparison purposes, with my 1060 GTX it permanently use less than 1% GPU and less than 10% CPU when opening Head Morph > Lod0 with thousands of entries.

Anyway, even if it hadn't improved your performance, swaping to Vulkan reduce compile time, file size and a little bit of CPU usage. So, it is clearly a win.

**Comment by mirh** [comment]
1.7.0 has ~8% rather than the previously reported 10%. 

But here's the crazy fun fact: when I put my laptop in optimus mode, my integrated gpu sits at 50%, while the dedicated one is on 30% again. 
And it doesn't stop until I close the program (or until I right click on the title bar, which I think stops the UI from running, while the context menu is open)

**Comment by mirh** [comment]
Sigh, it's not just this program
https://github.com/WerWolv/ImHex/issues/189

**Comment by mirh** [comment]
Well, turns out limiting framerate from *3000* (TIL) to 64 (I don't know why this odd number) really goes a long way into lowering usage. 
(though still far from what you'd expect a static window, let alone that when you drag it around the screen, it lags *sooo much*)

Still, for the aforementioned reasons, I guess like it's not really your fault specifically.. And I'd rather have you work on those other juicy feature requests than this frontend detail.
